import { faker } from '@faker-js/faker';
import fs from 'node:fs'; // File System module for writing to a file.
import path from 'node:path';

// use yargs to handle arguments:
// --count: number of products to generate
// --output: output to separate file or update db.json

import yargs from 'yargs/yargs';

const argv = yargs(process.argv.slice(2))
    .usage('Usage: $0 --count [count] --output [output]')
    .option('count', {
        alias: 'c',
        describe: 'Number of products to generate',
        type: 'number',
        default: 100
    })
    .option('output', {
        alias: 'o',
        describe: 'Output mode: "db" to update db.json, "file" to create a separate file',
        type: 'string',
        default: 'db'
    })
    .check((argv) => {
        if (argv.count <= 0) {
            throw new Error('Count must be a positive number');
        }
        if (argv.output !== 'db' && argv.output !== 'file') {
            throw new Error('Output must be either "db" or "file"');
        }
        return true;
    })
    .argv;

// Define the number of products to generate
const numberOfProducts = argv.count;


function generateRandomCategory() {
    const categories = [ // Defining common product categories found in online marketplaces. You can add more as per your requirements.
        'Electronics', 'Toys', 'Clothing', 'Grocery', 'Home & Garden',
        'Office Supplies', 'Health & Beauty', 'Pet Supplies', 'Automotive Accessories',
        'Furniture & Appliances', 'Sports & Outdoors', 'Books',
        "Gifts",'Musical Instruments','Art Supplies & Crafts','Jewelry & Watches',
        'Kitchenware & Dining Sets','Motorcycle Accessories','Computer Hardware & Peripherals',
        'Gadgets for Kids','Tools & Home Improvement'];
    return categories[Math.floor(Math.random() * categories.length)]; // Returning a random category from the defined list.
}

// Function to generate Product samples using Faker and write them into a JSON file.
function *generateProducts() {
    for (let i = 0; i < numberOfProducts; i++) {
        const product = { // Creating a new instance of the Product schema with random attributes generated by Faker.
            id: faker.number.int({ min: 1, max: 10000 }),
            name: faker.commerce.productName(),
            category: generateRandomCategory(),
            price: faker.commerce.price({ min: 10, max: 500 }), // Setting the price between 10 and 500 dollars
            stock: faker.number.int({ min: 1, max: 20 }), // Setting the stock to a random integer between 1 and 20
            description: faker.commerce.productDescription(),
        };

        yield product;
    }
}

const products = [...generateProducts()]; // Generate the products

if (argv.output === 'file') {
    // Write to a separate file
    fs.writeFileSync('products.json', JSON.stringify(products, null, 2));
    console.log(`Generated ${products.length} products and saved to products.json`);
} else {
    // Update db.json
    const dbPath = path.resolve(process.cwd(), 'db.json');

    // Read the existing db.json file
    let dbData = {};
    try {
        const dbContent = fs.readFileSync(dbPath, 'utf8');
        dbData = JSON.parse(dbContent);
    } catch (error) {
        console.log('No existing db.json found or invalid JSON. Creating a new one.');
    }

    // Add or update the products array in the db.json data
    dbData.products = products;

    // Write the updated data back to db.json
    fs.writeFileSync(dbPath, JSON.stringify(dbData, null, 2));
    console.log(`Generated ${products.length} products and added to db.json`);
}